DROP TABLE IF EXISTS jb_coin;
CREATE TABLE jb_coin(
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `code` VARCHAR(16) NOT NULL,
  `name` VARCHAR(32) NOT NULL
) COMMENT='币信息表';

DROP TABLE IF EXISTS jb_coin_ticker;
CREATE TABLE `jb_coin_ticker` (
  `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `pk` INT(11) NOT NULL,
  `coin` VARCHAR(16) NOT NULL,
  `price` DECIMAL(18,6) NOT NULL DEFAULT 0,
  UNIQUE(`pk`, `coin`)
) COMMENT='行情表';

DROP TABLE IF EXISTS jb_coin_rate;
CREATE TABLE `jb_coin_rate` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `coin` VARCHAR(16) NOT NULL,
  `pk` INT(11) NOT NULL,
  `rate` DECIMAL(18,6) NOT NULL DEFAULT '0.000000' COMMENT '涨幅',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pk` (`pk`,`coin`)
) ENGINE=INNODB AUTO_INCREMENT=415395 DEFAULT CHARSET=utf8 COMMENT='币值涨幅';

DROP TABLE IF EXISTS jb_coin_depth;
CREATE TABLE jb_coin_depth(
  id INT PRIMARY KEY AUTO_INCREMENT,
  pk INT NOT NULL,
  coin VARCHAR(16) NOT NULL,
  asks TEXT NOT NULL DEFAULT '' COMMENT '卖',
  bids TEXT NOT NULL DEFAULT '' COMMENT '买',
  UNIQUE(pk, coin)
) COMMENT '深度表';

DROP TABLE IF EXISTS jb_coin_depth_rate;
CREATE TABLE jb_coin_depth_rate(
  id INT PRIMARY KEY AUTO_INCREMENT,
  pk INT NOT NULL,
  coin VARCHAR(16) NOT NULL,
  price DECIMAL(18,6) NOT NULL,
  three_p INT NOT NULL DEFAULT 0 COMMENT '涨3%所需金额',
  five_p INT NOT NULL DEFAULT 0,
  eight_p INT NOT NULL DEFAULT 0,
  ten_p INT NOT NULL DEFAULT 0,
  twenty_p INT NOT NULL DEFAULT 0,
  three_m INT NOT NULL DEFAULT 0 COMMENT '跌3%所需金额',
  five_m INT NOT NULL DEFAULT 0,
  eight_m INT NOT NULL DEFAULT 0,
  ten_m INT NOT NULL DEFAULT 0,
  twenty_m INT NOT NULL DEFAULT 0,
  UNIQUE(pk, coin)
) COMMENT='涨跌幅度统计';
